### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by gbartoloni-florence** [edersouza38/insomnia-plugin-sfsf-samlassertion#1] opened 2023-08-17 09:06 UTC
Hi,
I just installed the plugin but it fails with the following stack trace:
```
Error: Cannot find module 'saml'
Require stack:
- /Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/src/samlAssertion.js
- /Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/app.js
- /Applications/Insomnia.app/Contents/Resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/src/samlAssertion.js:1:169)
    at Object.<anonymous> (/Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/src/samlAssertion.js:126:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/app.js:1:187)
    at Object.<anonymous> (/Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/app.js:2:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at wF (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-ae32ab7a.js:57:7484)
    at rE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-ae32ab7a.js:57:8229)
    at async u (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-ae32ab7a.js:193:32951)
```

Could you help me?

Thanks,
Giacomo

**Comment by edersouza38** [comment] 2023-08-17 13:09
Hi Giacomo, 

Thanks for reaching out. I've just experienced something similar when I've tried to install the plugin via the _Install Plugin_ button in the https://insomnia.rest/plugins/insomnia-plugin-sfsf-samlassertion link, but when I've closed Insomnia and opened it again I could use the plugin without issues. The installation process directly through Insomnia giving the npm package name insomnia-plugin-sfsf-samlassertion  (_Application_ -> _Preferences_ , tab _Plugins_) didn't need that, it ran without problems. For the time being I believe this can be an option; I'll check meanwhile what could be causing this.

Best regards,
Éder

**Comment by gbartoloni-florence** [comment] 2023-08-17 14:39
Hi Éder,
thanks for the quick response.
I've uninstalled the plugin roughly removing its folder from the plugins folder, then restarted insomnia and tried to install it following your instructions.
It gives this error:
```
Error: Error invoking remote method 'installPlugin': SystemError [ERR_FS_CP_EINVAL]: Invalid src or dest: cp returned EINVAL (cannot copy /var/folders/lh/t78jdgfx1557rr7_4x13ygphf38x25/T/insomnia-plugin-sfsf-samlassertion-1692282939975/uuid/dist/bin/uuid to a subdirectory of self /var/folders/lh/t78jdgfx1557rr7_4x13ygphf38x25/T/insomnia-plugin-sfsf-samlassertion-1692282939975/uuid/dist/bin/uuid) /Users/gbartoloni/Library/Application Support/Insomnia/plugins/insomnia-plugin-sfsf-samlassertion/node_modules/.bin/uuid
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
    at async onSubmit (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-ae32ab7a.js:195:513)
```

Thanks,
Giacomo

**Comment by edersouza38** [comment] 2023-08-25 07:54
Hi Giacomo,

Sorry for my late response. I've tried to reproduce the error above, but I couldn't since it is working on my current setup. Per the error above it seems you are using MacOS, is it right? Have you tried to install other plugins to check if they are successfully installed? If yes, I'll find somebody that has a MacBook so that I can check whether the plugin works as intended.

Regards,
Éder

**Comment by edersouza38** [comment] 2024-02-12 16:03
Closing due to missing feedback.

**Comment by edersouza38** [comment] 2024-02-12 16:03
Closing due to missing feedback.

**Closed as completed by edersouza38** 2024-02-12 16:03 UTC
